// ===================================
// Hero List - All Dota 2 Heroes
// ===================================

const heroes = [
    'abaddon', 'alchemist', 'ancient_apparition', 'anti-mage', 'arc_warden',
    'axe', 'bane', 'batrider', 'beastmaster', 'bloodseeker', 'bounty_hunter',
    'brewmaster', 'bristleback', 'broodmother', 'centaur_warrunner',
    'chaos_knight', 'chen', 'clinkz', 'clockwerk', 'crystal_maiden',
    'dark_seer', 'dark_willow', 'dawnbreaker', 'dazzle', 'death_prophet',
    'disruptor', 'doom', 'dragon_knight', 'drow_ranger', 'earthshaker',
    'earth_spirit', 'elder_titan', 'ember_spirit', 'enchantress', 'enigma',
    'faceless_void', 'grimstroke', 'gyrocopter', 'hoodwink', 'huskar',
    'invoker', 'io', 'jakiro', 'juggernaut', 'keeper_of_the_light', 'kez',
    'kunkka', 'legion_commander', 'leshrac', 'lich', 'lifestealer', 'lina',
    'lion', 'lone_druid', 'luna', 'lycan', 'magnus', 'marci', 'mars',
    'medusa', 'meepo', 'mirana', 'monkey_king', 'morphling', 'muerta',
    'naga_siren', "nature's_prophet", 'necrophos', 'night_stalker',
    'nyx_assassin', 'ogre_magi', 'omniknight', 'oracle', 'outworld_destroyer',
    'pangolier', 'phantom_assassin', 'phantom_lancer', 'phoenix',
    'primal_beast', 'puck', 'pudge', 'pugna', 'queen_of_pain', 'razor',
    'riki', 'ringmaster', 'rubick', 'sand_king', 'shadow_demon',
    'shadow_fiend', 'shadow_shaman', 'silencer', 'skywrath_mage', 'slardar',
    'slark', 'snapfire', 'sniper', 'spectre', 'spirit_breaker',
    'storm_spirit', 'sven', 'techies', 'templar_assassin', 'terrorblade',
    'tidehunter', 'timbersaw', 'tinker', 'tiny', 'treant_protector',
    'troll_warlord', 'tusk', 'underlord', 'undying', 'ursa',
    'vengeful_spirit', 'venomancer', 'viper', 'visage', 'void_spirit',
    'warlock', 'weaver', 'windranger', 'winter_wyvern', 'witch_doctor',
    'wraith_king', 'zeus'
];

// ===================================
// Hero Hints Database
// ===================================

const heroHints = {
    'abaddon': 'Attribute: Strength | Role: Support/Carry',
    'alchemist': 'Attribute: Strength | Role: Carry | Hint: Greedy farmer',
    'ancient_apparition': 'Attribute: Intelligence | Role: Support | Hint: Ice magic',
    'anti-mage': 'Attribute: Agility | Role: Carry | Hint: Magic hater',
    'arc_warden': 'Attribute: Agility | Role: Carry | Hint: Creates a copy',
    'axe': 'Attribute: Strength | Role: Initiator | Hint: Spins to win',
    'bane': 'Attribute: Intelligence | Role: Support | Hint: Nightmare',
    'batrider': 'Attribute: Intelligence | Role: Initiator | Hint: Rides a bat',
    'beastmaster': 'Attribute: Strength | Role: Initiator | Hint: Controls animals',
    'bloodseeker': 'Attribute: Agility | Role: Carry | Hint: Smells blood',
    'bounty_hunter': 'Attribute: Agility | Role: Support | Hint: Tracks enemies',
    'brewmaster': 'Attribute: Strength | Role: Initiator | Hint: Drunk fighter',
    'bristleback': 'Attribute: Strength | Role: Carry | Hint: Turn your back',
    'broodmother': 'Attribute: Agility | Role: Carry | Hint: Spider queen',
    'centaur_warrunner': 'Attribute: Strength | Role: Initiator | Hint: Half horse',
    'chaos_knight': 'Attribute: Strength | Role: Carry | Hint: Reality rift',
    'chen': 'Attribute: Intelligence | Role: Support | Hint: Holy persuasion',
    'clinkz': 'Attribute: Agility | Role: Carry | Hint: Burning archer',
    'clockwerk': 'Attribute: Strength | Role: Initiator | Hint: Mechanical hero',
    'crystal_maiden': 'Attribute: Intelligence | Role: Support | Hint: Freezing field',
    'dark_seer': 'Attribute: Intelligence | Role: Initiator | Hint: Vacuum ability',
    'dark_willow': 'Attribute: Intelligence | Role: Support | Hint: Fairy magic',
    'dawnbreaker': 'Attribute: Strength | Role: Support | Hint: Solar guardian',
    'dazzle': 'Attribute: Intelligence | Role: Support | Hint: Shallow grave',
    'death_prophet': 'Attribute: Intelligence | Role: Carry | Hint: Ghost swarm',
    'disruptor': 'Attribute: Intelligence | Role: Support | Hint: Storm rider',
    'doom': 'Attribute: Strength | Role: Carry | Hint: Silences with ult',
    'dragon_knight': 'Attribute: Strength | Role: Carry | Hint: Transforms into dragon',
    'drow_ranger': 'Attribute: Agility | Role: Carry | Hint: Frost arrows',
    'earthshaker': 'Attribute: Strength | Role: Initiator | Hint: Echo slam',
    'earth_spirit': 'Attribute: Strength | Role: Initiator | Hint: Rolling boulder',
    'elder_titan': 'Attribute: Strength | Role: Initiator | Hint: Astral spirit',
    'ember_spirit': 'Attribute: Agility | Role: Carry | Hint: Fire remnants',
    'enchantress': 'Attribute: Intelligence | Role: Support | Hint: Befriends creeps',
    'enigma': 'Attribute: Intelligence | Role: Initiator | Hint: Black hole',
    'faceless_void': 'Attribute: Agility | Role: Carry | Hint: Time walker',
    'grimstroke': 'Attribute: Intelligence | Role: Support | Hint: Ink magic',
    'gyrocopter': 'Attribute: Agility | Role: Carry | Hint: Flying machine',
    'hoodwink': 'Attribute: Agility | Role: Support | Hint: Squirrel archer',
    'huskar': 'Attribute: Strength | Role: Carry | Hint: Burning spears',
    'invoker': 'Attribute: Intelligence | Role: Carry | Hint: 10 spells',
    'io': 'Attribute: Strength | Role: Support | Hint: Wisp',
    'jakiro': 'Attribute: Intelligence | Role: Support | Hint: Two-headed dragon',
    'juggernaut': 'Attribute: Agility | Role: Carry | Hint: Blade fury',
    'keeper_of_the_light': 'Attribute: Intelligence | Role: Support | Hint: Light bringer',
    'kez': 'Attribute: Agility | Role: Carry | Hint: Dual weapon master',
    'kunkka': 'Attribute: Strength | Role: Carry | Hint: Admiral',
    'legion_commander': 'Attribute: Strength | Role: Carry | Hint: Duel master',
    'leshrac': 'Attribute: Intelligence | Role: Carry | Hint: Lightning storm',
    'lich': 'Attribute: Intelligence | Role: Support | Hint: Chain frost',
    'lifestealer': 'Attribute: Strength | Role: Carry | Hint: Infests units',
    'lina': 'Attribute: Intelligence | Role: Carry | Hint: Fire queen',
    'lion': 'Attribute: Intelligence | Role: Support | Hint: Finger of death',
    'lone_druid': 'Attribute: Agility | Role: Carry | Hint: Has a bear',
    'luna': 'Attribute: Agility | Role: Carry | Hint: Moon rider',
    'lycan': 'Attribute: Strength | Role: Carry | Hint: Werewolf',
    'magnus': 'Attribute: Strength | Role: Initiator | Hint: Rhino warrior',
    'marci': 'Attribute: Strength | Role: Carry | Hint: Silent fighter',
    'mars': 'Attribute: Strength | Role: Initiator | Hint: God of war',
    'medusa': 'Attribute: Agility | Role: Carry | Hint: Stone gaze',
    'meepo': 'Attribute: Agility | Role: Carry | Hint: Multiple clones',
    'mirana': 'Attribute: Agility | Role: Carry | Hint: Rides a tiger',
    'monkey_king': 'Attribute: Agility | Role: Carry | Hint: Staff wielder',
    'morphling': 'Attribute: Agility | Role: Carry | Hint: Water elemental',
    'muerta': 'Attribute: Agility | Role: Carry | Hint: Gunslinger',
    'naga_siren': 'Attribute: Agility | Role: Carry | Hint: Song puts to sleep',
    "nature's_prophet": 'Attribute: Intelligence | Role: Carry | Hint: Teleports anywhere',
    'necrophos': 'Attribute: Intelligence | Role: Carry | Hint: Death pulse',
    'night_stalker': 'Attribute: Strength | Role: Initiator | Hint: Stronger at night',
    'nyx_assassin': 'Attribute: Agility | Role: Initiator | Hint: Spiked carapace',
    'ogre_magi': 'Attribute: Intelligence | Role: Support | Hint: Two-headed caster',
    'omniknight': 'Attribute: Strength | Role: Support | Hint: Holy protector',
    'oracle': 'Attribute: Intelligence | Role: Support | Hint: False promise',
    'outworld_destroyer': 'Attribute: Intelligence | Role: Carry | Hint: Astral imprisonment',
    'pangolier': 'Attribute: Agility | Role: Initiator | Hint: Rolls into ball',
    'phantom_assassin': 'Attribute: Agility | Role: Carry | Hint: Critical strikes',
    'phantom_lancer': 'Attribute: Agility | Role: Carry | Hint: Many illusions',
    'phoenix': 'Attribute: Strength | Role: Initiator | Hint: Sun ray',
    'primal_beast': 'Attribute: Strength | Role: Initiator | Hint: Charges enemies',
    'puck': 'Attribute: Intelligence | Role: Initiator | Hint: Phase shift',
    'pudge': 'Attribute: Strength | Role: Initiator | Hint: Meat hook',
    'pugna': 'Attribute: Intelligence | Role: Carry | Hint: Life drain',
    'queen_of_pain': 'Attribute: Intelligence | Role: Carry | Hint: Sonic scream',
    'razor': 'Attribute: Agility | Role: Carry | Hint: Static link',
    'riki': 'Attribute: Agility | Role: Carry | Hint: Permanent invisibility',
    'ringmaster': 'Attribute: Intelligence | Role: Support | Hint: Circus performer',
    'rubick': 'Attribute: Intelligence | Role: Support | Hint: Spell steal',
    'sand_king': 'Attribute: Strength | Role: Initiator | Hint: Epicenter',
    'shadow_demon': 'Attribute: Intelligence | Role: Support | Hint: Creates illusions',
    'shadow_fiend': 'Attribute: Agility | Role: Carry | Hint: Soul collector',
    'shadow_shaman': 'Attribute: Intelligence | Role: Support | Hint: Hex and shackles',
    'silencer': 'Attribute: Intelligence | Role: Carry | Hint: Global silence',
    'skywrath_mage': 'Attribute: Intelligence | Role: Support | Hint: Mystic flare',
    'slardar': 'Attribute: Strength | Role: Initiator | Hint: Amplify damage',
    'slark': 'Attribute: Agility | Role: Carry | Hint: Shadow dance',
    'snapfire': 'Attribute: Strength | Role: Support | Hint: Rides a lizard',
    'sniper': 'Attribute: Agility | Role: Carry | Hint: Long range',
    'spectre': 'Attribute: Agility | Role: Carry | Hint: Haunts all enemies',
    'spirit_breaker': 'Attribute: Strength | Role: Initiator | Hint: Charge of darkness',
    'storm_spirit': 'Attribute: Intelligence | Role: Carry | Hint: Ball lightning',
    'sven': 'Attribute: Strength | Role: Carry | Hint: God strength',
    'techies': 'Attribute: Intelligence | Role: Support | Hint: Mines',
    'templar_assassin': 'Attribute: Agility | Role: Carry | Hint: Refraction',
    'terrorblade': 'Attribute: Agility | Role: Carry | Hint: Demon marauder',
    'tidehunter': 'Attribute: Strength | Role: Initiator | Hint: Ravage',
    'timbersaw': 'Attribute: Strength | Role: Carry | Hint: Timber chain',
    'tinker': 'Attribute: Intelligence | Role: Carry | Hint: Rearms items',
    'tiny': 'Attribute: Strength | Role: Carry | Hint: Grows bigger',
    'treant_protector': 'Attribute: Strength | Role: Support | Hint: Tree guardian',
    'troll_warlord': 'Attribute: Agility | Role: Carry | Hint: Switches axes/melee',
    'tusk': 'Attribute: Strength | Role: Initiator | Hint: Ice shards',
    'underlord': 'Attribute: Strength | Role: Support | Hint: Dark rift',
    'undying': 'Attribute: Strength | Role: Support | Hint: Tombstone',
    'ursa': 'Attribute: Agility | Role: Carry | Hint: Bear warrior',
    'vengeful_spirit': 'Attribute: Agility | Role: Support | Hint: Swaps positions',
    'venomancer': 'Attribute: Agility | Role: Support | Hint: Poison wards',
    'viper': 'Attribute: Agility | Role: Carry | Hint: Poison attack',
    'visage': 'Attribute: Intelligence | Role: Support | Hint: Stone familiars',
    'void_spirit': 'Attribute: Intelligence | Role: Carry | Hint: Void walker',
    'warlock': 'Attribute: Intelligence | Role: Support | Hint: Summons golem',
    'weaver': 'Attribute: Agility | Role: Carry | Hint: Time lapse',
    'windranger': 'Attribute: Intelligence | Role: Carry | Hint: Shackleshot',
    'winter_wyvern': 'Attribute: Intelligence | Role: Support | Hint: Ice dragon',
    'witch_doctor': 'Attribute: Intelligence | Role: Support | Hint: Death ward',
    'wraith_king': 'Attribute: Strength | Role: Carry | Hint: Reincarnation',
    'zeus': 'Attribute: Intelligence | Role: Carry | Hint: Thunder god'
};
